<!doctype html>
<html>
<head><meta charset="utf-8"><style>body{font-family: DejaVu Sans, sans-serif}</style></head>
<body>
    <h2>Exam Portal — Payment Receipt</h2>
    <p><strong>Receipt ID:</strong> {{ $payment->id }}</p>
    <p><strong>Student:</strong> {{ $user->name }} ({{ $user->email }})</p>
    <p><strong>Amount:</strong> ₹{{ number_format($payment->amount/100,2) }}</p>
    <p><strong>Payment ID:</strong> {{ $payment->razorpay_payment_id }}</p>
    <p><strong>Date:</strong> {{ $payment->created_at->format('d M Y H:i') }}</p>
    <hr/>
    <h4>Submission Details</h4>
    <table border="1" cellpadding="5" cellspacing="0" style="border-collapse: collapse; width: 100%;">
        <thead>
            <tr style="background-color:#f2f2f2;">
                <th>Field</th>
                <th>Value</th>
            </tr>
        </thead>
        <tbody>
            @php
                $submissionData = json_decode($submission->data);
            @endphp
            @foreach($submissionData as $key => $dt_val)
                <tr>
                    <td>{{ ucwords(str_replace('_', ' ', $key)) }}</td>
                    <td>{{ is_array($dt_val) ? implode(', ', $dt_val) : $dt_val }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>
    <footer><small>Generated by Exam Portal</small></footer>
</body>
</html>
